import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'leaflet/dist/leaflet.css'
import Navbar from "@/components/modules/Navbar";
import Topbar from "@/components/modules/Topbar";
import Footer from "@/components/modules/Footer";
import AosInt from "@/utils/aos";
import { authUser } from "@/utils/serverHelpers";
import ScrollToTop from "@/utils/ScrollToTop";
import NavbarClient from "@/components/modules/NavbarClient";
import FooterClient from "@/components/modules/FooterClient";
import TopbarClient from '@/components/modules/TopbarClient'






const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "IWJI Site",
  description: "Generated by create next app",
  icons: {
    img: '/images/Untitled-2-2-e1625120043428.png'
  }
};







export default async  function RootLayout({ children }) {
  

const user = await authUser()
console.log('layout user==>', user);


  return (
    <html lang="fa" dir='rtl' >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AosInt />
        <TopbarClient />
        <NavbarClient   isLogin={user ? true : false} />
   

        {children}
        <ScrollToTop/>
        <FooterClient />


      </body>
    </html>
  );
}
