const en={
pageTitle: "Automotive Industry",
      intro: `With total sales of €12 billion, the automotive industry accounts for approximately 20% of the total industrial output. Iran's automotive industry is the third largest active industry after oil and gas, contributing 10% of the country's GDP and employing 4% of the workforce (700,000 people). Iran significantly developed its automotive industry with an annual production of 200,000 vehicles before the revolution. After the 1979 revolution, production sharply declined due to the Iran-Iraq war and international sanctions. From the early 2000s, vehicle production in Iran grew significantly, surpassing one million vehicles in 2007-2008. Today, Iran produces over 1.6 million vehicles annually, ranking as the 20th largest car manufacturer in the world and one of the largest in Asia. In 2009, Iran ranked fifth in vehicle production growth alongside China, Taiwan, Romania, and India. According to OICA, production in 2013 dropped sharply to less than 750,000 cars and commercial vehicles.`,
      section1Title: "History of Vehicle Production",
      section1Desc: `By 2001, there were 13 public and private car manufacturers in Iran, with two companies, Iran Khodro and Saipa, producing 94% of domestic output. Iran Khodro, which produced the most common brand in the country – Peykan, replaced by Samand in 2005 – held 61% of the market in 2001, while Saipa produced 33% of total Iranian production. Iran Khodro is one of the largest car manufacturers in Asia and has established joint ventures with foreign partners across four continents.`,
      section2Title: "Types of Vehicles and Market Share",
      section2Desc: `Iranian manufacturers currently produce six types of vehicles including passenger cars, 4WD, trucks, buses, minibuses, and pickups. This sector directly employs about 500,000 people (approximately 2.3% of the workforce) and many others in related industries. About 75% of domestic production consists of passenger cars, with pickups next at around 15%. For maximizing potentials such as low weight and meeting environmental targets in the automotive industry, the choice of materials, composition, thickness, welding processes, and connections play a crucial role.`
    
}
export default en